# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaa6f5ca5a6450983e7ae21e045aae61c4824d06553418fce8702252c1d1e27c6518edc728821d64a9506bfc52bc6b6024eb9eafa2376ca25402131735b86ef4

test:
  secret_key_base: 3ba01c11bb5b4275a1584405902affd2a4fa43a232486ab2c69e9ddf190cebeb6c5be0119fc96c28ea5990804aa751667b0e02658fae3dde7627238f2450d796

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
